### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by Planeshifter** [math-io/log1p#1]

**Comment by kgryte** [comment]
Reviewed. You may want to do a once over before publishing.

**Comment by kgryte** [comment]
Ah, one thing that still needs to be done which is dependent on `math-polynomial` is to use that module for polynomial evaluation.

**Comment by Planeshifter** [comment]
Module has landed on npm, and uses `math-evalpoly` for polynomial evaluation. Thanks for reviewing!
